version: '3.8'

services:
  frontend:
    image: your-frontend-image
    build: ./frontend
    container_name: frontend-container
    networks:
      - app-network
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend/dist:/usr/share/nginx/html

  backend:
    image: your-backend-image
    build: ./backend
    container_name: backend-container
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:latest
    container_name: nginx-container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
