version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend-container
    networks:
      - app-network
    environment:
      - NODE_ENV=production
    expose:
      - 3000

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:latest
    container_name: nginx-container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
