FROM node:alpine

RUN apk add --no-cache nginx

WORKDIR /app

COPY package.json .
RUN npm install

COPY . .

COPY nginx.conf /etc/nginx/nginx.conf

COPY ./dist /var/www/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

