FROM node:alpine

# Устанавливаем PM2
RUN npm install -g pm2

WORKDIR /app

# Копируем только зависимости
COPY package.json package-lock.json ./

# Устанавливаем только продакшн-зависимости
RUN npm ci --only=production

# Копируем остальной код
COPY . .

# Открываем порт
EXPOSE 8000

# Запускаем напрямую backend
CMD ["pm2-runtime", "dist/index.js", "--name", "backend"]
